Add yolo_copy prefix to module names "models" and "utils"
Search and replace:
"from models" was replaced by "from yolo_copy.models"
"from utils" was replaced by "from yolo_copy.utils"

Still does not work:

M:\Dev\CXR\.venv\Scripts\python.exe -X pycache_prefix=C:\Users\Dzenan\AppData\Local\JetBrains\PyCharmCE2024.1\cpython-cache "C:/Program Files/JetBrains/PyCharm Community Edition 2021.1.1/plugins/python-ce/helpers/pydev/pydevd.py" --multiprocess --qt-support=auto --client 127.0.0.1 --port 53692 --file M:\Dev\CXR\Medical-SAM-Adapter\box_infer.py
Connected to pydev debugger (build 241.17890.14)
=> resuming from M:/Dev/CXR/LungAI/Data/Models/cxr_v2.pth
Namespace(net='sam', baseline='unet', encoder='default', seg_net='transunet', mod='sam_adpt', exp_name='cxr_v2', type='map', vis=1, reverse=False, pretrain=False, val_freq=5, gpu=True, gpu_device=0, sim_gpu=0, epoch_ini=1, image_size=256, out_size=256, patch_size=2, dim=512, depth=1, heads=16, mlp_dim=1024, w=4, b=2, s=True, warm=1, lr=0.0001, uinch=1, imp_lr=0.0003, weights='M:/Dev/CXR/LungAI/Data/Models/cxr_v2.pth', base_weights=0, sim_weights=0, distributed='none', dataset='cxr', sam_ckpt='M:/Dev/CXR/LungAI/Data/Models/cxr_v2.pth', thd=False, chunk=None, num_sample=4, roi_size=96, evl_chunk=None, mid_dim=None, multimask_output=1, data_path='./Data/', path_helper={'prefix': 'logs\\cxr_v2_2024_06_14_17_06_31', 'ckpt_path': 'logs\\cxr_v2_2024_06_14_17_06_31\\Model', 'log_path': 'logs\\cxr_v2_2024_06_14_17_06_31\\Log', 'sample_path': 'logs\\cxr_v2_2024_06_14_17_06_31\\Samples'})
YOLOv5  2024-6-14 Python-3.9.13 torch-2.3.0+cu121 CUDA:0 (NVIDIA GeForce RTX 3090, 24576MiB)

Traceback (most recent call last):
  File "M:\Dev\CXR\Medical-SAM-Adapter/yolo_copy\hubconf.py", line 50, in _create
    model = DetectMultiBackend(path, device=device, fuse=autoshape)  # detection model
  File "M:\Dev\CXR\Medical-SAM-Adapter\yolo_copy\models\common.py", line 467, in __init__
    model = attempt_load(weights if isinstance(weights, list) else w, device=device, inplace=True, fuse=fuse)
  File "M:\Dev\CXR\Medical-SAM-Adapter\yolo_copy\models\experimental.py", line 98, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location="cpu")  # load
  File "M:\Dev\CXR\.venv\lib\site-packages\torch\serialization.py", line 1025, in load
    return _load(opened_zipfile,
  File "M:\Dev\CXR\.venv\lib\site-packages\torch\serialization.py", line 1446, in _load
    result = unpickler.load()
  File "M:\Dev\CXR\.venv\lib\site-packages\torch\serialization.py", line 1439, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'models.yolo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "M:\Dev\CXR\Medical-SAM-Adapter/yolo_copy\hubconf.py", line 65, in _create
    model = attempt_load(path, device=device, fuse=False)  # arbitrary model
  File "M:\Dev\CXR\Medical-SAM-Adapter\yolo_copy\models\experimental.py", line 98, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location="cpu")  # load
  File "M:\Dev\CXR\.venv\lib\site-packages\torch\serialization.py", line 1025, in load
    return _load(opened_zipfile,
  File "M:\Dev\CXR\.venv\lib\site-packages\torch\serialization.py", line 1446, in _load
    result = unpickler.load()
  File "M:\Dev\CXR\.venv\lib\site-packages\torch\serialization.py", line 1439, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'models.yolo'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "M:\Dev\CXR\.venv\lib\site-packages\torch\hub.py", line 93, in _add_to_sys_path
    yield
  File "M:\Dev\CXR\.venv\lib\site-packages\torch\hub.py", line 597, in _load_local
    model = entry(*args, **kwargs)
  File "M:\Dev\CXR\Medical-SAM-Adapter/yolo_copy\hubconf.py", line 88, in custom
    return _create(path, autoshape=autoshape, verbose=_verbose, device=device)
  File "M:\Dev\CXR\Medical-SAM-Adapter/yolo_copy\hubconf.py", line 83, in _create
    raise Exception(s) from e
Exception: No module named 'models.yolo'. Cache may be out of date, try `force_reload=True` or see https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading for help.
python-BaseException

Process finished with exit code 1